Generate tweets from a content with VercelAI #928
wsvvrijheid/monorepo pull request #1002
Opened 2023-12-17 22:22 UTC by hakanayata

Post-generation using chatGPT-4
- API Route for streaming response
- Dynamic input fields (number of posts, character limit, and language)
- Response is rendered as textarea

2023-12-17 22:24 UTC, hakanayata commented
Please only take the following files into consideration:
- dashboard/pages/api/route-tweet-gen.ts
- dashboard/pages/[endpoint].tsx

2023-12-18 04:35 UTC, 7alip requested changes
Excellent job, thanks a lot.

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +              }
Could you please move these sections to a separate component, as we did with `PostSentenceForm`? You should probably also move the `useCompletion` hook part and all associated states to the new component. We can keep the `[endpoint]` page clean using this method.

This component may be useful elsewhere in the project, such as in samen.

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +                  />
You could wrap this with [`FormControl`](https://chakra-ui.com/docs/components/form-control/usage) component

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +                    <Box>
Can be wrapped with [`FormControl (Number input example)`](https://chakra-ui.com/docs/components/form-control/usage#number-input-example)

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +                    <Box flex='1'>
Can be wrapped with [FormControl (Select example)](https://chakra-ui.com/docs/components/form-control/usage#select-example)

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +                    Generate
You can add translations to all `common.json` files in each project.

```suggestion
                   {t('generate')}
```

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +                    Generate
The simplest way to add a new translation to the common.json files can be to use VSCode's global search and replace tool.

Search

```jsonc
"give-feedback": "Give feedback",
```

```jsonc
// "give-feedback": "Feedback geven",
// "give-feedback": "Geri Bildirimde Bulun",
```

Replace

```json
"generate": "Generate",
"give-feedback": "Give feedback",
```

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/api/route-tweet-gen.ts
> +
It seems some of the files are not formatted and there are whitespaces in the empty lines. You can investigate if it's default behavior of your editor.

If `format on save` setting doesn't work in your editor, you can run `yarn format` to format all the files in the project before you push.

```suggestion

```

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/tweet-gen.tsx
> +'use client';
This test page could be removed

2023-12-18 04:35 UTC, 7alip commented on apps/samenvvv/pages/tweet-gen.tsx
> +'use client';
This test page could be removed

2023-12-18 04:35 UTC, 7alip commented on .vscode/settings.json
> +  "liveServer.settings.port": 5501
You can stash these changes if you will need them in the future.

2023-12-18 04:35 UTC, 7alip commented on apps/api/config/database.ts
> +        port: '5433',
Please revert this and stash if you need

2023-12-18 04:35 UTC, 7alip commented on apps/api/docker-compose.yml
> +      - '5433:5433'
Should be reverted

2023-12-18 04:35 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +      console.log("Error: ", error.message.substring(0, 280));
You can use `toast` here for the users. Just display a generic error message `t('contact.form.failed')`. _(We can change the translation key to a generic key later.)_

2023-12-18 04:35 UTC, 7alip commented on apps/samenvvv/pages/api/route-tweet-gen.ts
> +        content: 'You are an activist, and your task is to raise awareness about human rights violations.'
Would it generate relative responses if alternative jobs were used, such as journalist, author, poet, and so on? If so, we can make it dynamic. It doesn't have to be in the UI now.

```ts
const { role = 'activist' } = await req.json()

content: `You are an ${role}, ...`
```

2023-12-18 04:39 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +              <Box p={4}>
Could you please move these sections to a separate component, as we did with `PostSentenceForm`? You should probably also move the `useCompletion` hook part and all associated states to the new component. We can keep the `[endpoint]` page clean using this method.

This component may be useful elsewhere in the project, such as in samen.

2023-12-18 12:53 UTC, 7alip requested changes

2023-12-18 12:53 UTC, 7alip commented on apps/api/package.json
>    "scripts": {
```
    "dev": "strapi dev",
    "dashboard": "strapi dev",
    "foundation": "strapi dev",
    "kunsthalte": "strapi dev",
    "samenvvv": "strapi dev",
```   

We need these script

2023-12-18 12:53 UTC, 7alip commented on apps/foundation/public/locales/en/common.json
> +"generate": "Generate",,
```suggestion
"generate": "Generate",
```

2023-12-18 12:53 UTC, 7alip commented on apps/kunsthalte/public/locales/en/common.json
> +"generate": "Generate",,
```suggestion
"generate": "Generate",
```

2023-12-18 12:53 UTC, 7alip commented on apps/lotus/public/locales/en/common.json
> +"generate": "Generate",,
```suggestion
"generate": "Generate",
```

2023-12-18 12:53 UTC, 7alip commented on apps/samenvvv/public/locales/en/common.json
> +"generate": "Generate",,
```suggestion
"generate": "Generate",
```

2023-12-18 12:53 UTC, 7alip commented on packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
> +        </Box>
Shall we display the completion for an effect? :)

```suggestion
        <Stack p={4}>
          <Progress size="xs" isIndeterminate />
          <Box color={'gray.500'}>{completion}</Box>
        </Box>
```

2023-12-18 14:48 UTC, hakanayata commented on packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
> +        </Box>
I'll replace completion for the progress bar then. 😎

2023-12-18 15:02 UTC, 7alip approved these changes
Thank you!

2023-12-18 15:11 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +              <TweetGenAI />
```suggestion
              <TweetGenAI content={(selectedContent as Post).content} />
```

If you want, you can still pass post's content data to use the default content.

2023-12-18 15:11 UTC, 7alip commented on packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
> +    body: {
```suggestion
    initialInput: content,
    body: {
```

2023-12-18 15:12 UTC, 7alip commented on packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
> +    },
```suggestion
    onFinish(prompt: string, completion: string) {
      setGeneratedPosts(JSON.parse(completion))
    },
    onError() {
      toastMessage('Error', t('contact.form.failed'), 'error')
    },
```

2023-12-18 15:16 UTC, 7alip commented on packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
> +              size="xs"
You can remove `size`, it looks so small.

2023-12-18 15:42 UTC, hakanayata commented on apps/samenvvv/pages/api/route-tweet-gen.ts
> +        content: 'You are an activist, and your task is to raise awareness about human rights violations.'
It seems like the profession plays a negligible role. The sentence after the comma does matter the most.

2023-12-18 17:17 UTC, 7alip commented on apps/samenvvv/pages/api/route-tweet-gen.ts
> +        content: 'You are an activist, and your task is to raise awareness about human rights violations.'
Thanks, I'll think about this later.

2023-12-18 19:31 UTC, merged