Add PostSentenceCreator component #1011
wsvvrijheid/monorepo pull request #1012
Opened 2023-12-20 14:52 UTC by hakanayata

A new component "PostSentenceCreator" added

2023-12-20 21:25 UTC, 7alip requested changes
Could you run `yarn format` before pushing your code. It seems there are some unformatted files have been merged into dev.

2023-12-20 21:25 UTC, 7alip commented on packages/ui/src/components/PostSentenceCreator/PostSentenceCreator.tsx
> +}
```suggestion
  initialContent?: string,
  colorScheme?: ThemeTypings['colorSchemes']
}
```

2023-12-20 21:25 UTC, 7alip commented on packages/ui/src/components/PostSentenceCreator/PostSentenceCreator.tsx
> +        colorScheme="purple"
If you don't provide any color scheme, buttons will use primary color as default.

```suggestion
        {...(colorScheme && { colorScheme })}
```

2023-12-20 21:25 UTC, 7alip commented on packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
> +                postId={postId}
We can apply purple color for PostSentenceCreator only in TweetGenAI component.

```suggestion
                postId={postId}
                colorScheme={'purple'}
```

2023-12-21 10:20 UTC, 7alip reviewed
Thanks

2023-12-21 10:20 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
> +                hashtag={(selectedModel as Post)?.hashtag as HashtagReturnType}
Wouldn't it be better only to provide `hashtagId` since we only need `id` in the component?

2023-12-21 11:16 UTC, 7alip commented on apps/dashboard/pages/[endpoint].tsx
>                <Stack p={{ base: 4, lg: 8 }}>
I noticed that we could refactor `PostSentenceForm` as well to receive `hashtagId` rather than `hashtag`. And change the condition where we render this block.

```tsx
const hashtagId = (selectedModel as Post)?.hashtag.id

{endpoint === 'posts' && selectedModel && hashtagId && (
 // ...
```

2023-12-21 14:47 UTC, 7alip requested changes
Could you provide the correct prop (hashtagId) in `PostSentenceModal` component?

2023-12-21 16:53 UTC, 7alip approved these changes
Thanks, do you want to merge it?

2023-12-21 17:11 UTC, merged

2023-12-21 17:11 UTC, hakanayata commented
> Thanks, do you want to merge it?

Sure, thank you.