ResponsiveCard design updated
wsvvrijheid/monorepo pull request #1031
Opened 2024-01-02 04:17 UTC by bbluechip

Changed ResponsiveCard design.

2024-01-02 21:01 UTC, 7alip reviewed
Thanks. I left a comment about your solution.

2024-01-02 21:01 UTC, 7alip commented on packages/ui/src/examples/E0_ResponsiveCard.tsx
> +  const isWideVersion = useBreakpointValue({ base: false, md: true });
`useBreakpointValue` uses JavaScript to calculate the viewport width under the hood. We focus on using pure css approach when making our components responsive.

For example, in plain css we use [media queries.](https://www.w3schools.com/css/css3_mediaqueries.asp). ChakraUI and some other competitors try to simplify using media queries.

**With ChakraUI**
```tsx
<Box width={{ base: "full", md: "50%", lg: "25%" }} /> // Object notation
// or
<Box width={["full", "full", "50%", "25%"] /> // Array notation
```

**With TailwindCSS**
```tsx
<div className="w-full md:w-1/2 lg:w-1/4"  />
```

**With plain css**
```css
div {
  width: 100%;
}

@media screen and (min-width: 30em) {
  div {
    width: 50%;
  }
}

@media screen and (min-width: 48em) {
  div {
    width: 25%;
  }
}
```

> Remember that the **Mobile First** approach uses `(min-width)` in the queries, while the **Desktop First** approach uses `(max-width)`. And most library uses mobile first approach.

2024-01-03 07:21 UTC, 7alip approved these changes
Thanks

2024-01-03 07:21 UTC, 7alip commented on packages/ui/src/examples/E1_FetchWithAxios.tsx
>    const [blogs, setBlogs] = useState([])
```suggestion
  const [blogs, setBlogs] = useState<Blog[]>([])
```

You can specify the type of the state. It helps.

2024-01-03 07:21 UTC, 7alip commented on packages/ui/src/examples/E1_FetchWithAxios.tsx
> +  )
It seems your code is not formatted. You can check if you have [EsLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) installed in VSCode. I recommend using VSCode. If you have any other IDE, you can investigate how to format your code based on the [prettier config](https://github.com/wsvvrijheid/monorepo/blob/main/.prettierrc) in the root of the project.

2024-01-03 07:22 UTC, 7alip requested changes

2024-01-03 07:22 UTC, 7alip commented on packages/ui/src/examples/E1_FetchWithAxios.tsx
> +    <div key={index}>{blog}</div>
`{blog}` is not renderable by React because it's an object. 

```suggestion
    <div key={index}>{blog.title}</div>
```

2024-01-04 02:21 UTC, 7alip commented on packages/ui/src/examples/E1_FetchWithAxios.tsx
> +  return
@bbluechip You won't see the results in Storybook, the reason is that you don't return the components but undefined because of unformatted code.

Please right click on the code and select `Format Document`. Make sure you have Prettier and ESlint extensions. When you format your code, you will notice that the JSX part of your component is unreachable.

| Original (unformatted)                                                                                 | Formatted                                                                                              | Correct                                                                                                |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------ |
| ![image](https://github.com/wsvvrijheid/monorepo/assets/22167684/308c2c48-0be4-46f8-bef3-6863a5fc5f9a) | ![image](https://github.com/wsvvrijheid/monorepo/assets/22167684/407143a9-0e26-449e-a0ad-4af32798de5b) | ![image](https://github.com/wsvvrijheid/monorepo/assets/22167684/683c9eac-0775-4649-8dca-550df9fa23c3) |

2024-01-04 02:27 UTC, 7alip commented on packages/ui/src/examples/E1_FetchWithAxios.tsx
> +  return
You can also see that the JSX has pale colors which means this part is not reachable because of the early return.

<img width="1286" alt="Screenshot 2024-01-04 at 03 24 19" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/3e636e9c-50fa-4f0e-a60a-265dbb7f43fa">

2024-01-04 19:37 UTC, 7alip commented on packages/ui/src/examples/E1_FetchWithAxios.tsx
> +          <li key={blog.id}>{blog.title}</li>
TypeScript probably complains about `blog.id` and `blog.title`, because blog type is not specified. You can indicate the blog state type as following:

```tsx
const [blogs, setBlogs] = useState<Blog[]>([])
```

2024-01-04 20:00 UTC, bbluechip commented
Added the interface of the Blog for not returning an error in useState line, need to specify but not defining a variable. 

Added response.data.data => First I thought respose.data would be enough but then I remembered, response.data is just the base returning data. Because of the api has data, meta objects. I need to write one more .data after response.data 

In this version FetchWithAxios running well.

2024-01-04 20:03 UTC, 7alip approved these changes
Thanks. You can close the task now :)

2024-01-05 21:46 UTC, 7alip reviewed
Thanks, I think you should just update your env variables or run your local server to make it work.

2024-01-05 21:46 UTC, 7alip commented on packages/ui/src/examples/E2_FetchWithStrapiRequest.tsx
> +        const response = await strapiRequest({
As the name suggests, `strapiRequest` is simply an axios wrapper for fetching data from our Strapi backend. It's a generic function (`function<T> {}`) that allows you to specify which type of Strapi model _(Blog, Activity, Hashtag etch)_ you want to retrieve data from.

```suggestion
        const response = await strapiRequest<Blog>({
```

2024-01-05 21:46 UTC, 7alip commented on packages/ui/src/examples/E2_FetchWithStrapiRequest.tsx
> +          token: PUBLIC_TOKEN,
You should specify the `locale` for some models, otherwise only the models in the default language (en) will be retrieved.

```suggestion
          locale: 'tr' // or preferably locale from useRouter()
          token: PUBLIC_TOKEN,
```

2024-01-05 21:46 UTC, 7alip commented on packages/ui/src/examples/E2_FetchWithStrapiRequest.tsx
> +          setBlogs(response.data.data as Blog[])
This statement is not necessary because `strapiRequest` should return as the following format: 
`{ data: [], pagination: {} }`


There are some other advanced debugging options, such as Network tab.

You can check to which endpoint are you making a request, what is your payload and what the server responses.

In your case, you are probably making a request to `http://localhost:1337`, which might not be running locally.

**You have some options to make it work:**

1. Update your env  `NEXT_PUBLIC_API_URL=http://localhost:1337` to`NEXT_PUBLIC_API_URL=https://wsvv-api-staging.onrender.com` in **packages/ui/.env**
2. Run your local server  by adding `"storybook": "strapi dev"` to your `apps/api/package.json` scripts.
3. Run your local server by running `cd apps/api && yarn dev`
4. If you are unable fix with these options, you can statically change API_URL in your strapiRequest function

<img width="1826" alt="Screenshot 2024-01-05 at 22 31 31" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/d02cba63-539c-43e7-b739-21d16f25607c">

2024-01-28 19:42 UTC, closed without merging