commit for review
wsvvrijheid/monorepo pull request #118
Opened 2022-09-01 14:48 UTC by yhtyyar94

2022-09-01 18:01 UTC, 7alip requested changes

2022-09-01 18:01 UTC, 7alip commented on apps/foundation/pages/club/collection/[slug].tsx
> +import { Container, Layout } from '@wsvvrijheid/ui'
Layout should be imported from foundation components not from our component library

2022-09-04 12:58 UTC, 7alip commented on apps/foundation/pages/club/collection/[slug].tsx
> +      ...(await serverSideTranslations(locale, ['common'])),
You forgot to provide next18nConfig. Building fails because of that. You can see other pages.

2022-09-04 13:03 UTC, yhtyyar94 commented on apps/foundation/pages/club/collection/[slug].tsx
> +      ...(await serverSideTranslations(locale, ['common'])),
ok i will fix it asap

2022-09-04 18:57 UTC, merged