Api auth serverless pages
wsvvrijheid/monorepo pull request #119
Opened 2022-09-02 11:28 UTC by slymny

2022-09-02 19:58 UTC, 7alip requested changes
Thank you. There are some small improvements.

Before merging it, I'll test them in real pages.

2022-09-02 19:58 UTC, 7alip commented on libs/utils/src/services/auth/getAuth.ts
> +  const response = await axios.post(`${API_URL}/api/auth/local`, {
We can maybe create a AuthResponse type for login response in `libs/types/src/auth.ts`

```ts
type AuthResponse = {
  jwt: string;
  user: {
    id: number;
    username: string;
    email: string;
    provider: string;
    confirmed: boolean;
    blocked: boolean;
    createdAt: string;
    updatedAt: string;
  };
};
```

```suggestion
  const response = await axios.post<AuthResponse>(`${API_URL}/...
```

2022-09-02 19:58 UTC, 7alip commented on libs/utils/src/services/auth/getAuth.ts
> +  const userId = response.data.user?.ids
Should be `id`

```suggestion
  const userId = response.data.user?.id
```

2022-09-02 19:58 UTC, 7alip commented on apps/admin/pages/api/auth/social-auth/[provider].ts
> +        const artistResponse = await request(token)({
```suggestion
        const artistResponse = await request(token)<Artist[]>({
```

2022-09-02 19:58 UTC, 7alip commented on apps/admin/pages/api/auth/social-auth/[provider].ts
> +        })
Probably it makes more sense to fetch the user by id.

```suggestion
        const response = await request(token)<User>({
          url: `api/users/${userId}`,
        })
```

2022-09-02 19:58 UTC, 7alip commented on apps/admin/pages/api/auth/reset-password.ts
> +      ;(req.session as Session).user = auth.user
This line seems unnecessary since we already pass auth object in the following line

2022-09-02 19:58 UTC, 7alip commented on apps/admin/pages/api/auth/register.ts
> +    req.session = auth as Session
It's safer to keep session props like `destroy` and `save`

```suggestion
    req.session = { ...auth, ...req.session }
```

2022-09-02 19:58 UTC, 7alip commented on apps/admin/pages/api/auth/social-auth/[provider].ts
> +          req.session = auth as Session
Again, it's safer to keep session props like `destroy` and `save` like you did in reset-password.

```suggestion
    req.session = { ...auth, ...req.session }
```

2022-09-02 19:58 UTC, 7alip commented on apps/admin/pages/api/auth/login.ts
> +    req.session = auth as Session
It's safer to keep session props like `destroy` and `save`

```suggestion
    req.session = { ...auth, ...req.session }
```

2022-09-02 20:36 UTC, slymny commented on libs/utils/src/services/auth/getAuth.ts
> +  const response = await axios.post(`${API_URL}/api/auth/local`, {
There are also artist, avatar, volunteer props in the response. Instead of adding this should I use existing User type and add non-existing props?
New suggestion: 
type AuthResponse = {
  jwt: string
  user?: User | null
  id: number | null
  createdAt: string | null
  updatedAt: string | null
}

2022-09-02 20:50 UTC, slymny commented on apps/admin/pages/api/auth/register.ts
> +    req.session = auth as Session
It's for casting. There is no problem with the other properties of the auth object, but only for the user. Is it safe to not cast at all? Because otherwise there is no casting.

2022-09-03 07:29 UTC, 7alip commented on libs/utils/src/services/auth/getAuth.ts
> +  const response = await axios.post(`${API_URL}/api/auth/local`, {
I'm not sure if the `post` request returns extended user data. We might need to adjust the backend for `/api/auth/local` request. Populated user data returns for the request `/api/users`

2022-09-03 07:38 UTC, 7alip commented on apps/admin/pages/api/auth/register.ts
> +    req.session = auth as Session
I remember req.session object has `save` and `destroy` property functions. I'm just curious if we re assign the session object, will we loose the function properties.

```ts
session = {
  save: () => void
  destroy => void
}
```

Then we try to reassign the session like:

```ts
session = {
  user: User
  token: string
  isLoggedIn: boolean
}
```

That's why I had to do the trick `auth as Session` because typescript was complaining about `save` and `destroy` props which are required props of the session from the library.

We could also do

session.auth = auth or (then adjust the Session type)
session.user = auth.user, session.token = auth.token, session.isLoggedIn = true

2022-09-05 12:15 UTC, merged