Feat/club page
wsvvrijheid/monorepo pull request #135
Opened 2022-09-09 17:44 UTC by rakin-tanis

2022-09-09 19:19 UTC, 7alip commented
@rakin-tanis Thanks for amazing work! 👏

I'll review it soon, but the only problem I noticed is, searchTerm is not always being cleaned from the url probably because of debouncing time. You can maybe check it if you find a time

2022-09-10 20:35 UTC, 7alip commented on libs/ui/src/templates/ArtClubTemplate/ArtClubTemplate.tsx
> +    username: auth.user?.username,
I don't think we want to search the arts by current authenticated user's usernaname.

```ts
const userFilter = {
    artist: {
      user: {
        username: {
          $containsi: searchTerm || username,
        },
      },
    },
  }
  ```

  As you can see in `userFilter`, searchTerm is filters for both username and art title. Do you think we should use `username` parameter in this case?

2022-09-10 20:40 UTC, 7alip commented on libs/ui/src/templates/ArtClubTemplate/ArtClubTemplate.tsx
> +  }, [])
Dependency array is empty. In which case it will refetch then?

I think, useArts has dynamic parameters. If I'm not mistaken, once any of these parameters changes, re-rendering will trigger refetching.

2022-09-10 21:28 UTC, 7alip requested changes
Thank you for your great efforts.
I noticed some points can be improved.

2022-09-10 21:28 UTC, 7alip commented on libs/utils/src/services/art/like.ts
> +    undefined
I don't remember why we wrote like this but wouldn't it also work like this:

`user && art.likers?.some(({ id }) => id === user.id))`

But let's skip this for now. We need to check `isLikedByUser` from the backend.

2022-09-10 21:28 UTC, 7alip commented on libs/ui/src/components/ArtCard/ArtCardBase.tsx
> +  const auth = useAuth()
We probably didn't noticed some points in the old code. I need to point out something about useAuth here:

`useAuth()` can make an api call each time we use it to check authentication. Until we find a better approach, I wouldn't recommend useAuth to be used in components, especially the components that are being rendered in a list, like Cards. I try to use it in page components and pass to the children.

But here, if you follow `auth`, we use it only in ArtWithDetails. Wouldn't it be better to use useAuth there?

My recommendation is:

- Move ArtModal into ArtCard. 
- Remove isModal prop. Pass href from ArtCard (href from ArtCardBaseProps)
- You don't need to change Navigate in this case. 
- Pass auth object to ArtModal from ArtCard.

2022-09-11 10:37 UTC, rakin-tanis commented on libs/ui/src/templates/ArtClubTemplate/ArtClubTemplate.tsx
> +    username: auth.user?.username,
you're right, I'll change it.

2022-09-11 11:10 UTC, rakin-tanis commented on libs/ui/src/templates/ArtClubTemplate/ArtClubTemplate.tsx
> +  }, [])
There was only the `searchTerm` parameter in the old code's dependency array of `useUpdateEffect`. After I added `searchTerm` as a `query parameter`, I removed it from the `useUpdateEffect` dependencies. Because as I know, every time `searchTerm` is changed, it is pushed as a query parameter and then the page is rendered again and `useArts` runs one time. I think you are partially right, we do not need `useUpdateEffect` anymore.

We send those parameters to the `useArts` hook:
**categories:  comes from url**
**page:  comes from url**
**searchTerm:  comes from url**
**locale:  comes from url**
populate: not change
pageSize: not change
sort: not change

The first four of them are pushed as the query parameters so, it causes the page to be rendered again, and it triggers `useArts` to run.

2022-09-11 11:33 UTC, rakin-tanis commented on libs/ui/src/components/ArtCard/ArtCardBase.tsx
> +          )}
it looks cleaner.

2022-09-11 11:48 UTC, rakin-tanis commented on libs/ui/src/hooks/useChangeParam.tsx
> +    ) {
if we change like that we can't send `0` or `true`, or `false` values as a query parameter.

2022-09-11 11:56 UTC, rakin-tanis commented on libs/utils/src/services/art/like.ts
> +    undefined
you're right, checking the length of the array is redundant here.

2022-09-12 20:42 UTC, 7alip approved these changes
I really appreciate your work 💯.

There were some conflicts with dev and I had to fix them. I also added `keepPreviousData` and loading for searchbar.

You can merge it if you want to.

2022-09-13 13:07 UTC, merged