Feat/create post form
wsvvrijheid/monorepo pull request #198
Opened 2022-09-27 23:39 UTC by MustafaTRKYLMZ

create tweet form added

2022-09-28 13:10 UTC, 7alip commented on package.json
> +    "string-similarity-js": "^2.1.4",
`string-similarity` seems to be more popular than the other. You can choose one of them and remove the other.

2022-09-28 13:19 UTC, 7alip commented on libs/ui/src/components/CreateTweetForm/types.ts
> +  onSubmitHandler: () => void
How will we get the form values from the component? We should be able to take the following props from the component:

`media, originalTweet, text`

> (recommender: number (userId)) can bi given from the session user data

```ts
// RecommendedTweet model
type RecommendedTweet = {
  recommender: number
  originalTweet: Tweet
  media: Blob
  text: string
}
```

2022-09-28 13:25 UTC, 7alip commented on libs/ui/src/components/CreateTweetForm/types.ts
> +  tweetContent: string
We will get `tweet data (original data from Twitter)` from human rights tweet timeline lists. I recommend passing all tweetData to the modal form instead of `tweetContent`. Because we will save `original tweetData` to our db as well.

2022-09-28 13:30 UTC, 7alip commented on libs/ui/src/components/CreateTweetForm/types.ts
> +  maxSize?: number
You can remove `maxSize`. I think we don't need to allow users to set the image size.

2022-09-28 13:33 UTC, 7alip commented on libs/ui/src/components/CreateTweetForm/CreateTweetForm.tsx
> +                  )}
I'm not sure if I understand this logic.

1. Why we show tweetImage only if there are more than 1 image? What about if there is only 1 tweet image?
2. Even there is a original tweet image, shouldn't we allow user to upload and recommend a new image. I think original image will always be available, because it will be in original tweetData. 
3. Shouldn't we always allow the users to be able to upload a new image.

2022-09-29 21:01 UTC, 7alip requested changes

2022-09-29 21:01 UTC, 7alip commented on libs/ui/src/components/CreateTweetForm/CreateTweetForm.stories.tsx
> +      isShared: false,
We didn't think they were necessary for the create mutation.

2022-09-30 09:15 UTC, MustafaTRKYLMZ commented on libs/ui/src/components/CreateTweetForm/CreateTweetForm.stories.tsx
> +        setImages={setImages}
I think it is necessary. Because It is normal in the real twitter account. We should upload according to real twitter

2022-09-30 19:28 UTC, 7alip commented on libs/ui/package.json
> +    "@types/string-similarity": "^4.0.0"
This should be in root package.json

2022-09-30 21:06 UTC, MustafaTRKYLMZ commented
It is ok

2022-09-30 21:07 UTC, merged