249-topiccard-share-buttons
wsvvrijheid/monorepo pull request #269
Opened 2022-11-13 07:36 UTC by MSKose

I couldn't get the placement="bottom" work for Popover, maybe it's some Storybook issue not sure. Rest should be ok

2022-11-13 11:18 UTC, 7alip requested changes
Thanks for the submission. It's almost done. You just need to fix a layout issue I mentioned and also make sure you don't get error when you run `yarn lint`

2022-11-13 11:18 UTC, 7alip commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +import {ShareButtons} from '@wsvvrijheid/ui'
You are in `ui` libs folder. NX warns:
`Projects should use relative imports to import from other files within the same project.`

You could import it from components `import { ShareButtons, WImage } from '../../components'`

2022-11-13 11:18 UTC, 7alip commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +              </PopoverTrigger>
There is a placement of the PopoverContent issue. After some investigation I discovered that `ActionButton` (as a children of `PopoverTrigger`) causes the problem.

My guess is: `ActionButton` doesn't receive `ref` attribute as it's not created with `React.forwardRef`.

There seems to be 2 solutions:

1. Refactor ActionButton with `forwardRef`
2. Easier way, just wrap ActionButton with an element, for example `Box` or `div`. So that, PopoverTrigger's children can receive ref.

```tsx
<PopoverTrigger>
  <Box>
    <ActionButton
      onClick={() => onShare()}
      icon={<AiOutlineShareAlt />}
      title="Share"
      isVertical={isVertical}
      variant="ghost"
    />
  </Box>
</PopoverTrigger>
```

2022-11-13 11:24 UTC, 7alip commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +              </PopoverTrigger>
I would use `placement=top` position. What do you think @MustafaTRKYLMZ?

2022-11-13 11:43 UTC, MSKose commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +import {ShareButtons} from '@wsvvrijheid/ui'
Asking out of curiosity, is there a reason explicit importing is prefered for these cases?

2022-11-13 11:51 UTC, Selman-S approved these changes

2022-11-13 11:59 UTC, MustafaTRKYLMZ commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +              </PopoverTrigger>
It doesn't work in my local. That is why, I couldn't test.

2022-11-13 12:03 UTC, MustafaTRKYLMZ commented
We should send limited text in to the twitter or other platform account. For example, after the 200 charakter we should add "..." It seems better than only word 
![image](https://user-images.githubusercontent.com/58182269/201520704-5d5fd447-cfab-4a10-a139-da11e346bacb.png)

2022-11-13 12:21 UTC, 7alip commented
> We should send limited text in to the twitter or other platform account. For example, after the 200 charakter we should add "..." It seems better than only word ![image](https://user-images.githubusercontent.com/58182269/201520704-5d5fd447-cfab-4a10-a139-da11e346bacb.png)

Normally It's not related to this issue. We should open a new issue for this bug. But if @MSKose wants to take this task as well, it's not a problem.

2022-11-13 19:34 UTC, 7alip approved these changes
Thanks.

I'm sorry for messing your PR up. :) I left a note about the new feature, you can merge your task if you want to revert your changes regarding three dots. Otherwise take your time to include it into `makeSocialContent` function.

2022-11-13 19:34 UTC, 7alip commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +                    quote={topic.description?.substring(0, 196) + '...' || ''}
I mentioned that this feature is unrelated to this PR because we should fix it in `ShareButtons` so that we don't have the same problem in other places where we use sharing buttons.

To truncate contents for Twitter, we use a custom utility function called `makeSocialContent` in ShareButtons. Perhaps you can modify this utility function to include `three dots (...)` at the end.

This function was written for use in our post maker app and to share something on Twitter using share buttons. You may include `three dots (...)` feature to this utility function in your current branch or undo your changes so that you or someone else can deal with it later in another issue.

2022-11-17 19:45 UTC, 7alip commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +import {ShareButtons} from '@wsvvrijheid/ui'
It's the first time for me to use monorepo as well. In normal projects you can also specify `import aliases` in tsconfig or jsconfig files. But when it comes to monorepo, it might be confusing to use aliases for internal imports. In our cases, we consider each project (libs) as an npm package 📦.

We could maybe use different alias for internal imports like `~components`. But you have to adjust `eslint` to  recognize your internal imports then.

2022-11-17 19:51 UTC, 7alip commented on libs/ui/src/admin/TopicCardBase/TopicCardBase.tsx
> +                    quote={topic.description?.substring(0, 196) + '...' || ''}
It looks the way better to me, but keep in mind that we can use `truncateText` function for SEO to generate descriptions from content. Let's keep it as it is now.

2022-11-17 19:57 UTC, 7alip commented
@MSKose I needed to make `pre-commit.sh` executable again and fix the conflicts. You can merge it.

2022-11-17 20:42 UTC, merged