TimeFormat is changed.
wsvvrijheid/monorepo pull request #391
Opened 2023-02-13 20:47 UTC by ertugrul-aydin

2023-02-15 19:50 UTC, 7alip requested changes
Thank you!

2023-02-15 19:50 UTC, 7alip commented on apps/samenvvv/components/HashtagCard/HashtagCard.tsx
> +        </Box>
Nice catch! I forgot that we have `FormattedDate` component 😄 

FaCalendarDay looks a bit bold to me. Can you try `HiOutlineCalendar` instead.

Using HStack (horizontal Flex with gap) might be better for vertical alignment.
```ts
<HStack>
  <Icon />
  <FormattedDate>
</HStack>
```

2023-02-16 13:29 UTC, ertugrul-aydin commented on apps/samenvvv/components/HashtagCard/HashtagCard.tsx
> +        </Box>
I updated icon and box elements 'HStack' instead.

2023-02-16 23:39 UTC, 7alip approved these changes
Thank you, it looks great now. Would you like to merge it?

2023-02-17 15:57 UTC, merged