Hashtag anounscements
wsvvrijheid/monorepo pull request #447
Opened 2023-03-05 06:37 UTC by MustafaTRKYLMZ

2023-03-05 19:42 UTC, 7alip requested changes
Thanks for hard work. I think we can simplify it, don't hasitate to ask if you have any question.

2023-03-05 19:42 UTC, 7alip commented on apps/post-maker/.expo/README.md
> +> Why do I have a folder named ".expo" in my project?
Expo files seem to be included from other branch and needs to be removed in this PR

2023-03-05 19:42 UTC, 7alip commented on apps/samenvvv/components/HashtagAnnouncement/HashtagAnnouncement.tsx
> +  link,
Wouldn't it be simpler just to pass `hashtag` itself as prop. 
You could still generate the link inside the component.

2023-03-05 19:42 UTC, 7alip commented on apps/samenvvv/components/HashtagAnnouncement/HashtagAnnouncement.tsx
> +    : undefined
1. variable names should be camelCase instead of PascalCase
2.  It's not always 2 hours difference. I would recommend using [date-fns-tz](https://github.com/marnusw/date-fns-tz) for different time zones

2023-03-05 19:42 UTC, 7alip commented on apps/samenvvv/pages/announcements.tsx
> +  )
It looks like a mapper function rather than hook. Therefore the name is confusing. Would be something like `mapHashtagToAnnouncement`

2023-03-05 19:42 UTC, 7alip commented on libs/ui/src/hooks/useAnnouncementData.tsx
> +      date: { name: 'Tarih: ', value: hashtag?.date },
I don't believe we should make it so complicated. I believe hashtag data could be used in the Announcement component without the need for a mapper.

Similar to the following:

```tsx
<Text>
  <strong>{t('topic')}</strong> {hashtag.title}
</Text>
<Text>
  <strong>{t('description')}</strong> {hashtag.description}
</Text>
.
.
.
```

2023-03-05 21:52 UTC, MustafaTRKYLMZ commented on apps/samenvvv/pages/announcements.tsx
> +  )
Where should we put this function? utils, hooks or?

2023-03-11 21:25 UTC, 7alip requested changes
Thanks. I noticed some parts that prevents samen from build.

Could you check `yarn build:samenvvv` works before pushing your changes?

2023-03-11 21:25 UTC, 7alip commented on apps/samenvvv/components/HashtagAnnouncement/HashtagAnnouncement.tsx
> +          quote={`${capsParams.text}\n\n${hashtag.content}\n\n`}
I don't think we should share the content.

> We shouldn't render `HashtagAnnouncement` if hashtag is not found. Build seems to fail because of `hashtag.content` where `hashtag` can be undefined.

```suggestion
          quote={`${capsParams.text}\n\n`}
```

2023-03-11 21:25 UTC, 7alip commented on apps/samenvvv/pages/announcements.tsx
> +      },
It's my mistake. We shouldn't render the page if hashtag is not found. Otherwise we might show some announcement content without any actual hashtag. This case doesn't make any sense. 

```suggestion
      notFound: true,
```

2023-03-11 21:25 UTC, 7alip commented on apps/samenvvv/pages/announcements.tsx
> +        />
Is it because twitter doesn't show the image with `og:image`? I remember had to add it in post page but it seems weird to me. I expect that twitter should show the image with `og:image` just like it shows in our legacy samen app.

2023-03-11 21:25 UTC, 7alip commented on apps/samenvvv/pages/announcements.tsx
> +import { HashtagAnnouncement } from '../components/HashtagAnnouncement' //TODO fix import style
```suggestion
import { Layout, HashtagAnnouncement } from '../components'
```

2023-03-11 21:25 UTC, 7alip commented on apps/samenvvv/pages/announcements.tsx
> +import { useTranslation } from 'react-i18next'
```suggestion
import { useTranslation } from 'next-i18next'
```

2023-03-11 21:25 UTC, 7alip commented on apps/samenvvv/pages/announcements.tsx
> +import i18nConfig from '..//next-i18next.config'
```suggestion
import i18nConfig from '../next-i18next.config'
```

2023-03-12 23:12 UTC, merged