Feat/art approval model
wsvvrijheid/monorepo pull request #46
Opened 2022-08-10 22:43 UTC by MustafaTRKYLMZ

artapprovalmodel added 
(not ready yet)

2022-08-11 08:39 UTC, 7alip requested changes
Thank you. There are some changes required.

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/types.ts
> +}
1. You forgot to give parameters to the functions.
2. `onEdit` is an internal action. We could set the state `isEditing = true` when we click Edit button. So that we can toggle art description text with a textarea. But I forgot to mention `onSave`. Because after editing we should be able to save the art. For now, let's disable `Edit` button or remove it, we can add the functionality later.


```ts
export type ArtApprovalModalProps = {
  onReject: (artId: number, editorId: number, feedback: string) => void
  onApprove: (artId: number, editorId: number, feedback: string) => void
  onDelete: (artId: number) => void
  art: Art
  user: User
  isOpen: boolean
  onClose: () => void
}
```

3. In general, it's better to give primitive props instead of object. By this way you can easily manipulate the prop in storybook. So it could even be better like this:

```ts
export type ArtApprovalFormTypes = {
  onReject: (artId: number, editorId: number, feedback: string) => void
  onApprove: (artId: number, editorId: number, feedback: string) => void
  onDelete: (artId: number) => void
  artId: number
  artTitle: string
  artDescription: string
  editorId: number
  editorName: string
  editorAvatar: string
  isOpen: boolean
  onOpen: () => void
}
```

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/index.tsx
> +export * from './ArtApprovalModel'
```suggestion
export * from './ArtApprovalModal'
```

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalModel.stories.tsx
> +  //   const actions: ArtActions = {
Could you remove comments

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                              >
Is Stack necessary here?

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                                </MenuItem>
You don't need to use custom styling for buttons. It's always better to use `size`, `colorScheme` etc to have consistent button design.

```tsx
<MenuItem
  as={Button}
  onClick={handleDelete}
  variant="ghost"
  colorScheme="red"
  icon={<HiOutlineX />}
>
  Delete
</MenuItem>;
```

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                                  icon={<BiEditAlt w={3.5} h={3.5} />}
Icon component's are not from Chakra, so we can't use chakra style props in non-chakra components. `<HiOutlineX w={3.5} h={3.5} />`. You should remove it.

It's not necessary here but just keep in mind, for example in case you want to make the icon bigger you could do `<Box as={BEditAlt} boxSize={3.5} />` etc.

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                            onClick={() => handleReject('reject')}
Approve and Reject buttons could have `w="full"` to fill the space

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                          spacing={[2, 4, 6, 8]}
4 is enough. 6 and 8 seems a bit large to me.

```suggestion
                          spacing={4}

```

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                          size={['sm', 'md', 'lg', 'xl']}
Not necessary I think

```suggestion
```

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                      ></Avatar>
1. Could be self-closed tag
2. Instead of using w/h, Avatar has `size` prop. `size="sm"` is better.
3. `src` should be the avatar

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                      h={'136px'}
```suggestion
```

Giving fixed height is not a good practise for responsive design.

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                  <Flex align="start" justify={'start'} w="full" h={'72px'}>
- [ ] `maxH` is better in case art has a short description.
- [ ] You could also show long and short description cases in storybook

```suggestion
                  <Flex align="start" justify={'start'} w="full" maxH={'72px'} overflow='auto'>
```

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                    ></Avatar>
Same comments as the other Avatar

2022-08-11 08:39 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                          onChange={handleInputChange}
You should store `feedback` note in state to be able to send it through `onApprove` or `onReject`

```suggestion
                          onChange={e => setFeedback(e.target.value)}

```

2022-08-11 16:26 UTC, MustafaTRKYLMZ commented on libs/ui/src/admin/ArtApprovalModel/ArtApprovalForm.tsx
> +                      ></Avatar>
I know first avatar should take avatar as src, but current art has not avatar. Maybe we should create it

2022-08-12 05:48 UTC, 7alip requested changes
Thanks for improving.

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                <VStack align={'start'} justify="space-between">
`VStack` is ofter being used to center the items horizontally. That's why you need to set `align=start`. I always prefer using `Stack` instead.

```tsx
<Stack spacing={4}>
  <Stack spacing={4}>
```

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                    maxH={'72px'}
I thing there is enough space for description. You can increase it, maybe 150 or even more? 

- [ ] Remember adding story for a very large description to test it.

```tsx
const LongDescription = Template.bind({})
LongDescription.args = { artDescription: "Give a long lorem ipsum text here" }
```

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                <VStack align={'start'} w={'full'}>
If parent component would be `Stack`, you wouldn't need to give align and width here. You can replace all `VStack`'s with `Stack`

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                      />
Avatar has `name` attribute. If src image doesn't exist, it shows the initials of the given name. It's better to always give `name` to an Avatar.

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +  }
```suggestion
  const handleApprove = () => {
    onApprove(artId, editorId, feedback)
  }
```

Click functions doesn't have to have parameters, since we get them from state or props. For example we have `artId, editorId` from props and `feedback` from the state. You don't need to pass them again:

```tsx
// Instead of
onClick={() => handleApprove(...)}
onClick={handleApprove)
```

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +              <Stack w={'full'}>
If we have a large description, the image will be smaller I think. Could you test it?

```suggestion
            <Stack direction={['column', 'row']} spacing={4}>
              <Stack w={'full'} minW="50%">
```

You can also use SimpleGrid

```suggestion
            <SimpleGrid columns={{base: 1, lg: 2}} spacing={4}>
              <Stack>
```

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                    <Avatar size="sm" src="https://bit.ly/dan-abramov" />
Src should be provided from props here. Even if we don't have `artistAvatar` in our mock data, we can give `https://bit.ly/dan-abramov` in storybook. Otherwise we can't provide real image coming from the API.

Remember name attribute!

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                            _hover={{ bg: 'red.400' }}
I prefer using chakra button themes. Because if we update our global theme later, we will always have the same button styles everywhere. You should usually avoid giving custom styles. Consider this for other buttons too.

```tsx
colorScheme='red'
w='full'
```

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                            ></MenuButton>
If Button doesn't have any text, it's better to use IconButton to center the icons.

```tsx
aria-label="Open art menu"
as={IconButton}
icon={<HiDotsVertical />
colorScheme='primary'
```

2022-08-12 05:48 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +  // editorName,
Can you use them in the component? Even if we don't have mock data for it, we can always test with random image or text via props in storybook

2022-08-12 09:53 UTC, MustafaTRKYLMZ commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                    maxH={'72px'}
I tested that there isn't any problem. It is using scroll with long text.

2022-08-13 17:44 UTC, 7alip requested changes
Thank you, it's almost done. We still need some small improvements

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtFeedbackForm.tsx
> +                    onClick={() => isEdit}
Can you remove isEdit prop?

We can implement edit/save feature later in another task.

---

An example implementation of editing mode:

```tsx
// editing state
const [isEditing, setIsEditing] = useState(false)
const [description, setDescription] = useState(art.description)

// Edit button
<MenuItem
  onClick={() => setIsEditing(true)}
>
Edit
</MenuItem>

{isEditing 
  // // Textarea and save on edit mode
  ? <Stack>
      <TextArea onChange={e => setDescription(e.target.value)} />
      <Button onClick={() => onSave(description)}>Save</Button>
    </Stack>
  : <Text>{description}</Text>
}

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtFeedbackForm.tsx
> +                    _hover={{ bg: 'blue.400', color: 'white' }}
_hover is not necessary and colorScheme shouldn't be red, maybe primary

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtFeedbackForm.tsx
> +                    _hover={{ bg: 'red', color: 'white' }}
No need any hover effect

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/types.ts
> +  isEdit: boolean
You can remove isEdit as we will control it with state later

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/types.ts
> +  artImages: []
```suggestion
  artImages: UploadFile[] // or string[]
```

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/types.ts
> +  artArtistName: string
artistName is enough I think

2022-08-13 17:44 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/types.ts
> +  artAvatar: string
Do you mean artistAvatar?

2022-08-13 17:49 UTC, 7alip requested changes

2022-08-13 17:49 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +      <Modal onClose={onClose} size={['1088px']} isOpen={isOpen}>
```suggestion
      <Modal onClose={onClose} size="6xl" isOpen={isOpen}>
```

I'm not sure we can give size as pixels.

2022-08-13 17:49 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalModel.stories.tsx
> +longDescription.args = {
Prefer PascalCase names `LogDescription`

Can you also test vertical and horizontal oriented images?
https://picsum.photos/960/540
https://picsum.photos/540/960

2022-08-13 23:22 UTC, MustafaTRKYLMZ commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalModel.stories.tsx
> +longDescription.args = {
I tried multi art but there is a problem here. And also ArtDeail component has a problem with splide component which is someone created before. 
I am trying to find solution now. Do you have any idea about this problem?

2022-08-14 03:56 UTC, 7alip requested changes

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +      <Modal onClose={onClose} size="6xl" isOpen={isOpen}>
I found how we can increase the modal size. If we want to have a larger modal we can do it by resizing the ModalContent. You can remove size here.

```tsx
<ModalContent maxW='95vw' maxh='95vh'>
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +export const ArtApprovalForm: FC<ArtApprovalFormTypes> = ({
Could you rename the component and file names to `ArtApprovalModal`?

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                <Stack align={'start'} justify="space-between">
Maybe it's better to remove align='start'. Stack has 'stretch' by default and all the children will be fullwidth. You can see that on edit mode we don't have fullwidth textarea

```tsx
{/* ..... ==============================*/}
<Stack spacing={4} justify="space-between">
  <Stack spacing={4}>
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                          onClick={() => onSave(description)}
Instead of having fullwidth "Save" button, we can align it to right.

```suggestion
                          onClick={() => onSave(description)}
                          alignSelf="end"
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +import '@splidejs/splide/dist/css/themes/splide-default.min.css'
Component doesn't seem to be right place for css. We should add it in the projects' root component `_app.tsx` or `main.tsx` etc.

Could you check if it works if you add it in stories file?

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +          <ModalBody>
Vertical and horizontal paddings doesn't seem to be the same.

```suggestion
          <ModalBody p={{ base: 2, lg: 4 }}>
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                      <SplideSlide key={index}>
Can you confirm if it's better to have centered images?

```suggestion
                      <Center as={SplideSlide} key={index}
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                  <Flex align="start" justify="start" w="full" h={8}>
Is flex necessary here?

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalModel.stories.tsx
> +  // artImages: ART_MOCKS?.data[0]?.images.map((image) =>{
```tsx
artImages: [
    {
      ...IMAGE_MOCK,
      url: 'https://i.picsum.photos...',
    },
  ]
```

or

```tsx
artImages: [{ url: 'https://i.picsum.photos...' }] as UploadFile[]
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalModel.stories.tsx
> +  artImages: [
You can use a simple hack as we only need url for the images

```tsx
artImages: [{ url: 'https://i.picsum.photos...' }] as UploadFile[]
```

2022-08-14 03:56 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtFeedbackForm.tsx
> +                    Edit{' '}
```suggestion
                    Edit

```

2022-08-14 07:16 UTC, MustafaTRKYLMZ commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                      <SplideSlide key={index}>
When we give Center, Splide component doesn't working.

2022-08-14 09:12 UTC, 7alip commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                      <SplideSlide key={index}>
I mean `<Center as={SplideSlide} key={index}>` not only `<Center key={index}>`

2022-08-14 10:00 UTC, MustafaTRKYLMZ commented on libs/ui/src/admin/ArtApprovalModal/ArtApprovalForm.tsx
> +                      <SplideSlide key={index}>
Yes I tried something. But splide css didn't work.

2022-08-14 22:46 UTC, merged