Admin PageHeader
wsvvrijheid/monorepo pull request #48
Opened 2022-08-12 10:12 UTC by yhtyyar94

2022-08-12 13:41 UTC, MustafaTRKYLMZ commented
I think pull request should open from current branch to **dev**

2022-08-12 14:57 UTC, 7alip commented
> I think pull request should open from current branch to **dev** . That is why there is lots of problem. You should reopen this pr **from Admin-PageHeader to dev**

I've changed it to dev. You can always edit to change the target branch.

<img width="1311" alt="Screenshot 2022-08-12 at 16 56 26" src="https://user-images.githubusercontent.com/22167684/184382414-6c5c8666-e658-4649-bc98-b36a33750163.png">

2022-08-12 15:36 UTC, 7alip requested changes
Thank you, nice job! 

Can you try to apply the changes and test all the functions like `alert("Filter clicked)`?

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +  textColor: string
We don't need text color here. Each project will have it's own `primary` color. Default primary color is `blue` from chakra. Just put the primary color to the header text.

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +  backgroundColor: string
You can remove backgroundColor as well. Let's keep it transparent by default.

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +  createNew: () => void
I think you should have added `buttons` `filters` and `sorts` instead of single action. 

Explained in #39 

```tsx
type PageHeaderProps = {
  title: string
  onSearch?: (value: string) => void
  filterMenu?: MenuItemProps[] // or ComponentProps<typeof MenuItem>[]
  sortMenu?: MenuItemProps[]
  buttons?: ButtonGroups[] // or ComponentProps<typeof Button>[]
}
```

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +      <Text color={textColor} w={{ base: '40%' }} fontWeight={'bold'}>
Width is needed here?: 

Also, `base` applies from 0px bearkpoint if you don't give any other breakpoints. It's probably the same think as `w="40%"`. You can read an explanation about responsive styles here: https://github.com/wsvvrijheid/monorepo/pull/47#discussion_r944140256

```suggestion
      <Text color="primary.400"  fontWeight={'bold'}>
```

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +        </Flex>
https://chakra-ui.com/docs/components/input/usage#add-elements-inside-input

You could use InputGroup, InputLeftElement for the icon to get more consistent design. You wouldn't need to give onFocus onBlur effects in this case.

We mostly use default Chakra component. We can later update our component styles in theme, so that all the components will have the same design.

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +              borderRadius={'50%'}
```suggestion
              size="lg" // 
              rounded="full"
```

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +              <MenuItem>Filter by Published</MenuItem>
We should be able to set filtering options from props. Each page can have different filtering options and functions. That's why we want to create a generic Header.

You can apply the same approach for sortMenu and buttons

```tsx
{filterMenu.map(filterItem => 
  <MenuItem {...filterItem} />
}
```

2022-08-12 15:36 UTC, 7alip commented on libs/ui/src/Admin/PageHeader.tsx
> +        </Button>
You can render buttons here.

```tsx
{buttons && 
  <ButtonGroup>
    {buttons.map(button => <Button {...button} />)}
  </ButtonGroup>
}
```

2022-08-16 05:19 UTC, 7alip commented
Hey @yhtyyar94, hope you don't mind that I refactored your code to make the component more generic.

Could you review it (https://github.com/wsvvrijheid/monorepo/pull/48/commits/eec8ca23e5b901b46b5a560cb715968b7c382a36) and then merge if everything is ok?

2022-08-16 13:42 UTC, merged