Tweet card
wsvvrijheid/monorepo pull request #55
Opened 2022-08-16 17:39 UTC by yhtyyar94

2022-08-16 22:59 UTC, 7alip requested changes
Thank you. I mentioned about some important points. Could you update the code?

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +    <Grid
Is there any chance to convert `Grid` and `GridItem`s to `Stack` and `HStack` to make it simpler?

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +      w={'460px'}
`width` should be removed. We always need `100%` width elements to make it responsive. We will be using the component in columns and grids. We can always control the width in it's parent component.

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +        <Avatar src={tweet.user.profile} />
Avatar should have `name` prop to display name initials in case there is no avatar image available.

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +            <BsPatchCheckFill color="#1da1f2" size={'15px'} />
```suggestion
```

Lets skip the verification icon. Not every account has that one. We can maybe later show it related info is provided in the data. _(Just a reminder: Avoid using custom colors in most cases. We have twitter.500 color for example)_

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +            </MenuButton>
Wouldn't it be easier to use default IconButton instead of using custom styles?

```tsx
<MenuButton
  aria-label='Tweet actions'
  as={IconButton}
  variant={'ghost'}
  size='sm'
  icon={<BsThreeDots />}
/>
```

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +            {options && <MenuList>{options}</MenuList>}
We can put a fixed options here (Edit + Save menu items). We don't need to make it customizable.

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +        </HStack>
Do wee really need to wrap the text with HStack (flex div)?

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +          </HStack>
Again, do we need to use HStack?

What about using `<WImage ratio='twitter' .../>`?

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +            <iframe
In our other project (samenvvv) we have TweetWidget component in which we use a tweet card. Maybe you can apply the similar design we made there. If it will be complex we can skip showing videos for now.

https://github.com/wsvvrijheid/monorepo/blob/e0aeb5c6d8280049ec130618d6129ddabfa381bd/libs/ui/src/postMaker/TweetWidget/TweetWidget.tsx#L59-L70

2022-08-16 22:59 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/TweetCardBase.stories.tsx
> +    </MenuOptionGroup>
As I explained in the component, we could just provide onEdit and onSave here and just alert the passed data. e.g. `onSave=(tweet => JSON.stringify(tweet)`

You need to move the MenuItems into the component. But keep in mind, we don't need MenuOptionGroup, just regular MenuList and MenItems.

Also please use the way Chakra shows in the documentation

```tsx
<MenuItem icon={<FaPencil />} onClick={() => onEdit(tweet)}>
    Edit
</MenuItem>
```

2022-08-17 15:31 UTC, yhtyyar94 commented on libs/ui/.storybook/tsconfig.lib.json
> +{
i do not know for some reason i did not able to push my codes, the error was in that file, if no need to that file i can delete

2022-08-17 16:36 UTC, 7alip commented on libs/ui/src/Admin/TweetCard/types.ts
> +import { Tweet } from '../../../../types/src/tweet'
You're right. We forgot to export Tweet. You can add `export * from './tweet'` into `libs/types/src/index.ts`

2022-08-17 16:38 UTC, 7alip commented on libs/ui/.storybook/tsconfig.lib.json
> +{
Let's remove it for now. Before merging we can check it again. We will also need to revert removing .husky folder change.

2022-08-17 19:09 UTC, yhtyyar94 commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +            <iframe
we did not have react-player package so i installed it

2022-08-18 00:23 UTC, yhtyyar94 commented on libs/ui/src/Admin/TweetCard/TweetCardBase.tsx
> +            <BsPatchCheckFill color="#1da1f2" size={'15px'} />
ok good to know that, where can i find pre defined colors, styles... in our project folder

2022-08-18 00:30 UTC, 7alip approved these changes
Thank you very much.
I [added](https://github.com/wsvvrijheid/monorepo/pull/55/commits/cb88d785ccc983da11bd93168f5f78e133a443cb) tweet mocks. You can review it and merge if it's ok.

2022-08-18 00:33 UTC, yhtyyar94 commented
ok after making last changes upon the request i will merge

2022-08-18 02:37 UTC, merged