added stripe single payment and subscription methods to the donation …
wsvvrijheid/monorepo pull request #696
Opened 2023-07-06 00:21 UTC by yhtyyar94

…page

local stripe webhook url http://localhost:3000/api/payment/status

2023-07-06 07:18 UTC, 7alip requested changes
There are TS issues. yarn build will give you where the problems are.

It's probably best to remove `@mollie` package first which cause confusion. It seems we use both Stripe and Mollie. If it's the case, I mean if we use Stripe for subscription and Mollie for regular payments, we need to keep track of the types.

2023-07-06 17:28 UTC, 7alip commented on apps/foundation/pages/api/payment/status.ts
>  const handler: NextApiHandler = async (req, res) => {
Where do we use this `/api/payment/status` endpoint?

2023-07-06 17:30 UTC, yhtyyar94 commented on apps/foundation/pages/api/payment/status.ts
>  const handler: NextApiHandler = async (req, res) => {
we use this endpoint for stripe webhooks

2023-07-09 03:11 UTC, 7alip commented on apps/foundation/pages/api/payment/status.ts
>  const handler: NextApiHandler = async (req, res) => {
I mean at which point we call this endpoint in our code?

2023-07-09 04:32 UTC, 7alip commented on apps/dashboard/pages/api/payment/index.ts
> +      success_url: `${SITE_URL}/donation/complete?id=${donation.id}`,
```
success_url: `${SITE_URL}/donation/complete?status=success&id=${donation.id}&session_id={CHECKOUT_SESSION_ID}`
```

Stripe adds `CHECKOUT_SESSION_ID` to success url. Isn't it more secure to use it in complete page? Because Strapi ids are numbers, anyone can trigger this success page `/complete?id=50`. The previous Mollie implementation was insecure.

2023-07-26 19:01 UTC, 7alip commented on apps/dashboard/pages/api/payment/index.ts
>  const handler: NextApiHandler = async (req, res) => {
We use the same functionality for each app. I think it's better to create a function in `@wsvvrijheid/stripe` and use it in the apps.

```ts
// packages/stripe/src/stripePaymentHandler.ts
export const stripePaymentHandler: NextApiHandler = async (req, res) => {
```


```ts
// api/payment/index.ts
export default stripePaymentHanler
```

You can do it for `api/payment/status` as well.

2023-07-26 19:46 UTC, 7alip approved these changes
Thanks for amazing job, you can merge it

2023-07-26 19:53 UTC, merged