Aktivities in platforms website
wsvvrijheid/monorepo pull request #782
Opened 2023-08-09 19:47 UTC by MustafaTRKYLMZ

2023-08-09 21:05 UTC, 7alip commented on apps/api/src/api/activity/content-types/activity/schema.json
> +      "type": "boolean"
Why we have both `platforms` relation and `forLotus`, `forKunsthalte` booleans.

`forPlatform` boolean approach was an alternative way to relation. We should chose one of them. I prefer using `platforms` relation approach.

2023-08-09 21:10 UTC, 7alip commented on packages/ui/src/data/schemas/activity.ts
> +  { name: 'forLotus', type: 'boolean',label:'Publish to Lotus vd Media' },
If we use `platforms` relation, these fields should be replaced with `platforms` multi select.

2023-08-09 21:11 UTC, 7alip commented on packages/types/src/activity.ts
>  type ActivityRelation = {
Did you forget to add `platforms` relation as type?

2023-08-09 21:15 UTC, MustafaTRKYLMZ commented on packages/types/src/activity.ts
>  type ActivityRelation = {
> Did you forget to add `platforms` relation as type?
I don't understand that. I thought that forKunsthalte and forLotus are enought.

2023-08-09 21:31 UTC, 7alip commented on packages/types/src/activity.ts
>  type ActivityRelation = {
In the [old issue](https://github.com/wsvvrijheid/monorepo/issues/403) I meantioned `forPlatform` approach but in my opinion `platforms` approach is better as we discussed in the [new issue](https://github.com/wsvvrijheid/monorepo/issues/758).

`platforms` relation is more flexible and in the future, if there are more platforms we can easily update platform relation.

2023-08-10 21:38 UTC, 7alip requested changes
Thanks, great!

2023-08-10 21:38 UTC, 7alip commented on apps/foundation/pages/platforms/index.tsx
> +  console.log('platforms BBBBBB', platforms)
Console could be removed

2023-08-10 21:38 UTC, 7alip commented on apps/kunsthalte/pages/activities/index.tsx
> +  console.log('aktivities :::', activities)
Console could be removed

2023-08-10 21:38 UTC, 7alip commented on packages/types/src/activity.ts
> +  platforms?: number
```suggestion
  platforms?: number[]
```

2023-08-10 21:38 UTC, 7alip commented on packages/ui/src/admin/ModelForm/utils.ts
> +            activityModel?.platforms?.map(c => ({
```suggestion
            activityModel?.platforms?.map(p => ({
```

2023-08-10 21:39 UTC, 7alip commented
@MustafaTRKYLMZ You can merge after finishing the small changes

2023-08-11 11:37 UTC, 7alip commented on apps/foundation/pages/platforms/index.tsx
> +  console.log('platforms BBBBBB', platforms)
Is the console still there?

2023-08-11 11:40 UTC, 7alip commented on apps/kunsthalte/pages/activities/index.tsx
> +  fields: ['title', 'description', 'slug'],
It's better not to use fields here. We might need date or other data in the future for cards

2023-08-11 11:41 UTC, MustafaTRKYLMZ commented on apps/foundation/pages/platforms/index.tsx
> +  console.log('platforms BBBBBB', platforms)
I deleted. But Maybe I forgot.

2023-08-11 11:42 UTC, MustafaTRKYLMZ commented on apps/kunsthalte/pages/activities/index.tsx
> +  fields: ['title', 'description', 'slug'],
It was before. If it is not nessesary, I can delete.

2023-08-11 18:51 UTC, 7alip commented on apps/foundation/pages/platforms/index.tsx
> +  console.log('platforms BBBBBB', platforms)
It seems you forgot to delete it.

2023-08-11 18:52 UTC, 7alip commented on apps/kunsthalte/pages/activities/index.tsx
> +  fields: ['title', 'description', 'slug'],
Not necessary for now. It might be necessary when we update the Card

2023-08-11 19:14 UTC, merged