donations-list
wsvvrijheid/monorepo pull request #789
Opened 2023-08-13 13:26 UTC by GOZTURK7

2023-08-13 17:56 UTC, 7alip requested changes
Thanks

2023-08-13 17:56 UTC, 7alip commented on packages/ui/src/data/tables/donation.tsx
> +        rejected: 'red',
`aproved` `pending` `rejected`: We use these approval statuses for our translatable data (such as activities, blogs, hashtags etc). 

The type of donation status is different than ApprovalStatus and it's a result of [Stripe webhooks]([Stripe webhooks](https://github.com/wsvvrijheid/monorepo/blob/c5630fdaf538bb0a12ed0016461dcf885c579113/packages/stripe/src/donation/webhook.ts#L9C14-L9C14)).  If the status is paid, we can change the colour to green; otherwise, the status could be yellow.

```ts
return {
    variant: 'outline',
    colorScheme: (value as string) === 'paid' ? 'green' : 'yellow',
}
```

2023-08-13 17:56 UTC, 7alip commented on packages/ui/src/admin/AdminNav/useAdminNav.tsx
> +      label: tAdmin('donationList'),
Do we have this `donationList` key in `admin.json`? 

I would change `donationList` to `donations`;

Each project has public/locales folder. Whenever we add a new translation, we need to make sure if the key exists in `admin.json` or `common.json` for **every project**.

```
const { t } = useTranslation() // => common.json
const { t: tAdmin } = useTranslation('admin') // => admin.json
```

2023-08-13 17:56 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +    pageSize: 10,
You can increase page size, maybe 50 is fine

2023-08-13 17:56 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +    //   ...(searchTerm && { [`title_${locale}`]: { $containsi: searchTerm } }),
You can activate filter but only for email search is enough for now.

```ts
...(searchTerm && { email: { $containsi: searchTerm } })
```

2023-08-13 17:56 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +  const status = query.status as ApprovalStatus
status filter can be removed

2023-08-13 17:56 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +  }) as Donation[]
You return the donation data without modifying it. Mapping has no effect in this situation and could be removed.

2023-08-13 17:56 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +        ]}
`sortMenu` could also be removed

2023-08-13 17:56 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +        // onSuccess={artsQuery.refetch}
comments could be removed

2023-08-13 20:27 UTC, 7alip approved these changes
You can merge after removing the comments

2023-08-13 20:27 UTC, 7alip commented on packages/ui/src/data/tables/donation.tsx
> +  // },
Comments could be removed

2023-08-13 20:27 UTC, 7alip commented on packages/ui/src/data/tables/donation.tsx
> +// import { LocaleBadges} from '../../admin'
Comments could be removed

2023-08-13 20:27 UTC, 7alip commented on packages/ui/src/data/tables/donation.tsx
> +  email: {},
Shall we make `email` sortable as well?

2023-08-13 20:28 UTC, 7alip commented
@GOZTURK7 Remember adding keys to json files

2023-08-13 20:58 UTC, 7alip commented on packages/ui/src/data/tables/donation.tsx
> +  email: {sortable: true},
It's not formatted!

2023-08-14 07:09 UTC, MustafaTRKYLMZ commented
Is it possible to change sort type? Last donation must be top of the table. Default sort esc can be better.

2023-08-14 16:47 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +  useEffect(() => setCurrentPage(1))
> If `useEffect` hook doesn't have any dependency array, the effect function will be called on every render of the component. This can lead to performance issues and unexpected behavior. It is recommended to always specify the dependencies array to ensure that the effect is only executed when the dependencies have changed. If there are no dependencies, you can pass an empty array [] to ensure that the effect is only executed once, when the component mounts.

```suggestion
  useEffect(() => setCurrentPage(1), [])
```

2023-08-14 20:18 UTC, 7alip approved these changes
Thanks

2023-08-14 20:18 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +  const [sort, setSort] = useState(['createdAt:desc'] as any)
You can merge after this adjustment

```suggestion
  const [sort, setSort] = useState<Sort>(['createdAt:desc'])
```

2023-08-14 21:12 UTC, merged