Cookie Banner for All Apps
wsvvrijheid/monorepo pull request #809
Opened 2023-08-27 16:13 UTC by ertugrul-aydin

2023-08-27 17:14 UTC, 7alip requested changes
Thanks

2023-08-27 17:14 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>          </Navigate>
We can use `<Trans />` component here.

Current translation:
`By using our website, you agree to the use of cookies as described in our Cookie Policy. <a>Cookie Policy<a/>`

With Trans:
`By using our website, you agree to the use of cookies as described in our <a>Cookie Policy</a>`

```tsx
<Trans 
  i18nKey={'cookie.text'} 
  components={{ a: <Navigate href="/privacy" /> }}
/>
```

In this case you can remove `cooki.policy-url` key from translations.

2023-08-27 17:17 UTC, 7alip requested changes
Thanks

2023-08-27 17:17 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
> +      left="0"
If it's rounded, I prefer to have some space around the banner

```suggestion
      bottom="2"
      right="2"
      left="2"
```

2023-08-27 17:17 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>          <Square size="12" bg="lightgray" borderRadius="md">
You can remove bg color

```suggestion
        <Square size="12" borderRadius="md">
```

2023-08-27 19:36 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>        bg="gray.700"
Darker color would be better.

```suggestion
      bg="gray.900"
```

2023-09-01 22:49 UTC, ertugrul-aydin commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>          </Navigate>
Navigate is not working. In this way, text can not be clicked. 

`  <Text color="white" fontSize={{ base: 'sm', md: 'md' }}>
        <Trans
          i18nKey={'cookie.text'}
          components={{
            a: (
              <Navigate
                href={'/privacy'}
                _hover={{ transform: 'scale(2.1)', color: 'primary.400' }}
                pl="2"
              />
            ),
          }}
        />
      </Text>`

2023-09-02 03:41 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>          </Navigate>
You might have forgotten to update the translations:

`Cookie Policy` should be wrapped with `a` tag: `"cookie.text": "... described in our <a>Cookie Policy</a>."`

Remember you should restart your dev server (`yarn foundation`) when you change your translations.

Please also remove `{t('cookie.policy-url')}`

<img width="883" alt="Screenshot 2023-09-02 at 05 36 19" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/ebc469bb-c6a5-4ff2-9ee9-f998582670c2">

2023-09-02 07:12 UTC, 7alip reviewed
Thanks. Just one thing about `isMobile`

2023-09-02 07:12 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>            ...(isMobile && { width: '100%' }),
I overlooked this part.

Perhaps, the main reason of the hydration issue was using `isMobile`.

`isMobile` works only in the client side. We should avoid using client-only statements for styling or rendering parts. This usually trigger hydration error unless you use dynamic import.

`width` is core css attribute and could be used with regular responsive syntax:

`width={{ base: "full", sm: "auto" }}`

2023-09-02 07:12 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
> +        <Square size="12" borderRadius="md">
The same `isMobile`.

We could use `display={{ ... }}`

2023-09-02 07:12 UTC, 7alip commented on packages/ui/src/components/CookieBanner/CookieBanner.tsx
>    const isMobile = useBreakpointValue({ base: true, md: false })
You can remove `isMobile`.

This breakpoint hook can be used in functions or some other situations which will not be triggered in the initial load.

2023-09-03 21:38 UTC, 7alip approved these changes
Thanks,  you can add the privacy pages in a separate branch later if you want. You can merge this

2023-09-04 03:51 UTC, 7alip commented
I'll merge this to see if the same font loading issue will occur in dev deployment.

2023-09-04 03:51 UTC, merged

2023-09-04 03:56 UTC, 7alip commented
@ertugrul-aydin Font issue seems to be fixed in dev. Feel free to create a new branch for privacy pages