MonthPicker is added
wsvvrijheid/monorepo pull request #834
Opened 2023-09-12 22:07 UTC by ertugrul-aydin

I added MonthPicker. I noticed also that clear button is not working yet on the MonthPicker component. Additionally, it seems that it needs to make some modifications to the filters by including '$lte' for it to work correctly.

2023-09-12 23:04 UTC, 7alip requested changes
Thank you

2023-09-12 23:04 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +  const [month, setMonth] = useState<Month>()
`month.startYear` seems weird. State name could be something like `date`, `range` or `dateRange`

```suggestion
  const [date, setDate] = useState<Month>()
```

2023-09-12 23:04 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +}
There is already `RangeParams` from MonthPicker

2023-09-12 23:04 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +      <MonthPicker onRangeSelect={handleSelect} />
`MonthPicker` should be children of `PageHeader`

```tsx
<PageHeader>
  <MonthPicker />
</PageHeader>

2023-09-12 23:04 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +      <MonthPicker onRangeSelect={handleSelect} />
It seems we're not able to use clear method outside of the component.

To fix this, you can add `onClear` prop to MonthPicker. Whenever user clicks `Clear` button, you can both clear internal state and execute `onClear` function.

2023-09-13 11:14 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +            .padStart(2, '0')}-01T00:00:00.000Z`,
`new Date(2023, 01).toISOString() // 2023-01-31T23:00:00.000Z`

2023-09-13 12:31 UTC, ertugrul-aydin commented
![Ekran Resmi 2023-09-13 14 29 12](https://github.com/wsvvrijheid/monorepo/assets/48697010/9ecfab90-0e31-499a-addb-f9475ad04872)


Should 'Select Current' button work ? I think I should activate 'on Select' for this. It wasn't in this issue.

2023-09-13 13:33 UTC, 7alip commented
> ![Ekran Resmi 2023-09-13 14 29 12](https://user-images.githubusercontent.com/48697010/267651313-9ecfab90-0e31-499a-addb-f9475ad04872.png)
> 
> Should 'Select Current' button work ? I think I should activate 'on Select' for this. It wasn't in this issue.

Actually it's the issue of `MonthPicker` component itself. You don't need to fix in this task. We can create a new task to improve MonthPicker.

2023-09-13 13:35 UTC, 7alip approved these changes
Thank you.

I'm aware of some bugs with MonthPicker but we can fix it in a separate task.

You can merge it **after changing `lte` to `lt`**

2023-09-13 13:35 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +          $lte: endDate,
```suggestion
          $lt: endDate,
```

`lestThanEqual` will include the first day of the next month.

2023-09-13 18:28 UTC, merged