Add Total Amount Feature to Donations Page
wsvvrijheid/monorepo pull request #840
Opened 2023-09-16 23:31 UTC by ertugrul-aydin

2023-09-17 20:57 UTC, 7alip reviewed
Thanks

2023-09-17 20:57 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +      >
You don't need to show the children if `totalAmount` doesn't exist

2023-09-17 20:57 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +        </Flex>
Having `Spacer`s along with `textAlight=right` seems overkill to me.

Can something like this work:

```tsx
<Flex justify="end">
  <Box />
</Flex>
```

2023-09-17 21:31 UTC, 7alip commented on packages/ui/src/admin/DataTables/DataTable.tsx
> +      {tableProps.data.length > 0 && children}
What if we want to display something as DataTable children even though there is no data?

2023-09-17 21:31 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +      >
I would control displaying totalAmount here instead of `{tableProps.data.length > 0 && children}`.

2023-09-17 21:47 UTC, ertugrul-aydin commented on apps/dashboard/pages/donations.tsx
> +      >
Yes, you are right. i will make the change.

2023-09-17 21:47 UTC, ertugrul-aydin commented on packages/ui/src/admin/DataTables/DataTable.tsx
> +      {tableProps.data.length > 0 && children}
Yes, you are right. i will make the change.

2023-09-17 23:36 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +import { useUpdateEffect, Box, Spacer, Text, Flex } from '@chakra-ui/react'
Lint error, Spacer is defined but never used

```suggestion
import { useUpdateEffect, Box, Text, Flex } from '@chakra-ui/react'
```

2023-09-17 23:37 UTC, 7alip approved these changes
Thanks

2023-09-18 10:36 UTC, 7alip commented
> If I see correct, amount show paid and unpaid amount. If it true, It should be changed. We need only paid amount.

@MustafaTRKYLMZ Shouldn't we adjust it with status filter?  I don't know if it makes sense but we can still see what is the total amount of unpaid transactions.

2023-09-18 10:39 UTC, ertugrul-aydin commented
> If I see correct, amount show paid and unpaid amount. If it true, It should be changed. We need only paid amount.

I've updated it to display both 'paid' and 'unpaid' amounts separately. What do you think about this ? I have shared screenshot below.

![Ekran Resmi 2023-09-18 12 32 46](https://github.com/wsvvrijheid/monorepo/assets/48697010/22320f16-144a-4296-b4de-7378b0457d97)

2023-09-18 10:44 UTC, 7alip commented
> I've updated it to display both 'paid' and 'unpaid' amounts separately. What do you think about this ? I have shared screenshot below.

It's also fine for me, thanks

2023-09-18 11:50 UTC, MustafaTRKYLMZ commented
> > If I see correct, amount show paid and unpaid amount. If it true, It should be changed. We need only paid amount.
> 
> @MustafaTRKYLMZ Shouldn't we adjust it with status filter? I don't know if it makes sense but we can still see what is the total amount of unpaid transactions.

In mijn opinion We don't need unpaid amount. I think paid amount is enought. For example one person can try lots of time.

2023-09-21 19:41 UTC, 7alip requested changes
We decided to display always only paid donations. Can you make the changes?

2023-09-21 19:41 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +      }, 0)
Our conclusion is to list only paid transactions. So we don't need this part

2023-09-21 19:41 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +              Total Unpaid: <Text as="b">{totalUnpaid}</Text>
Remove unpaid part

2023-09-21 19:41 UTC, 7alip commented on apps/dashboard/pages/donations.tsx
> +  const totalPaid =
Update donationsQuery filter, only fetch them based on paid status.

`totalPaid` can be renamed to `totalAmount`

2023-09-30 15:29 UTC, 7alip reviewed
Thank you,

There are some conflicts. Would you prefer to resolve them yourself?

2023-10-01 20:08 UTC, merged