join page
wsvvrijheid/monorepo pull request #91
Opened 2022-08-26 21:14 UTC by rakin-tanis

2022-08-26 21:59 UTC, 7alip requested changes

2022-08-26 21:59 UTC, 7alip commented on libs/ui/src/templates/JoinTemplate/JoinTemplate.tsx
> +import { toastMessage } from '../../../../utils/src/util/toast'
```suggestion
import { toastMessage } from '@wsvvrijheid/utils'
```

2022-08-26 21:59 UTC, 7alip commented on libs/ui/src/templates/JoinTemplate/JoinTemplate.tsx
> +import { mutation, request } from '../../../../utils/src/lib'
```suggestion
import { mutation, request } from '@wsvvrijheid/utils'
```

2022-08-26 21:59 UTC, 7alip commented on libs/utils/src/util/toast.ts
> +})
Do we have to give `theme` here?

https://chakra-ui.com/getting-started/migration#2-update-createstandalonetoast

Also keep in mind that we need to add `<ToastContainer />` in `preview.tsx` to make the toast work.

2022-08-27 10:33 UTC, rakin-tanis commented on libs/utils/src/util/toast.ts
> +})
I am not sure about `theme`, I copied the code directly from wsvvriheid. It is not mandatory giving params to `createStandaloneToast`. I can remove it.

There is a `_app.tsx` file in `/apps/foundation/pages/_app.ts` and it contains `<ToastContainer />`, I suppose you mean it.

2022-08-27 10:52 UTC, 7alip commented on libs/ui/src/templates/JoinTemplate/JoinTemplate.stories.tsx
> +import { JoinTemplate, JoinTemplateProps } from '.'
I'm not sure if it causes circular dependency error but I would import them from their own files like following:

```suggestion
import { JoinTemplate } from './JoinTemplate'
import { JoinTemplateProps } from './types'
```

2022-08-27 10:52 UTC, 7alip commented on libs/ui/src/templates/JoinTemplate/JoinTemplate.stories.tsx
> +import { JoinTemplate, JoinTemplateProps } from '.'
And if you don't have multiple component files in the folder, you don't need to create `types.ts`, you can put the type in the component file.

2022-08-28 22:58 UTC, merged